// AUTO-GENERATED FILE. DO NOT MODIFY.
// This file is auto-generated by the Ballerina OpenAPI tool.

// Copyright (c) 2024, WSO2 LLC. (http://www.wso2.org).
//
// WSO2 LLC. licenses this file to you under the Apache License,
// Version 2.0 (the "License"); you may not use this file except
// in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

import ballerina/data.jsondata;
import ballerina/http;
import ballerinax/sap;

# Consumers of this inbound service can create, read, update, and delete condition records inside condition record, validity of condition record, pricing scale, and condition supplement.
public isolated client class Client {
    final sap:Client clientEp;

    # Gets invoked to initialize the `connector`.
    #
    # + config - The configurations to be used when initializing the `connector` 
    # + hostname - Hostname of the S/4HANA system, without the scheme 
    # + port - Port the service is reachable on 
    # + return - An error if connector initialization failed 
    public isolated function init(ConnectionConfig config, string hostname, int port = 443) returns error? {
        string serviceUrl = string `https://${hostname}:${port}/sap/opu/odata/sap/API_SLSPRICINGCONDITIONRECORD_SRV`;
        http:ClientConfiguration httpClientConfig = {auth: config.auth, httpVersion: config.httpVersion, http1Settings: config.http1Settings, http2Settings: config.http2Settings, timeout: config.timeout, forwarded: config.forwarded, followRedirects: config.followRedirects, poolConfig: config.poolConfig, cache: config.cache, compression: config.compression, circuitBreaker: config.circuitBreaker, retryConfig: config.retryConfig, cookieConfig: config.cookieConfig, responseLimits: config.responseLimits, secureSocket: config.secureSocket, proxy: config.proxy, socketConfig: config.socketConfig, validation: config.validation, laxDataBinding: config.laxDataBinding};
        self.clientEp = check new (serviceUrl, httpClientConfig);
    }

    # Reads all condition supplements in the system.
    #
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Retrieved entities 
    remote isolated function listA_SlsPrcgCndnRecdSuplmnts(map<string|string[]> headers = {}, *ListA_SlsPrcgCndnRecdSuplmntsQueries queries) returns CollectionOfA_SlsPrcgCndnRecdSuplmntWrapper|error {
        string resourcePath = string `/A_SlsPrcgCndnRecdSuplmnt`;
        map<Encoding> queryParamEncoding = {"$orderby": {style: FORM, explode: false}, "$select": {style: FORM, explode: false}, "$expand": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Creates one or more condition supplements.
    #
    # + headers - Headers to be sent with the request 
    # + payload - New entity 
    # + return - Created entity 
    remote isolated function createA_SlsPrcgCndnRecdSuplmnt(CreateA_SlsPrcgCndnRecdSuplmnt payload, map<string|string[]> headers = {}) returns A_SlsPrcgCndnRecdSuplmntWrapper|error {
        string resourcePath = string `/A_SlsPrcgCndnRecdSuplmnt`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Reads a specific condition supplement.
    #
    # + ConditionRecord - Number of Condition Record
    # + ConditionSequentialNumber - Sequential number of the condition
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Retrieved entity 
    remote isolated function getA_SlsPrcgCndnRecdSuplmnt(string ConditionRecord, string ConditionSequentialNumber, map<string|string[]> headers = {}, *GetA_SlsPrcgCndnRecdSuplmntQueries queries) returns A_SlsPrcgCndnRecdSuplmntWrapper|error {
        string resourcePath = string `/A_SlsPrcgCndnRecdSuplmnt(ConditionRecord='${getEncodedUri(ConditionRecord)}',ConditionSequentialNumber='${getEncodedUri(ConditionSequentialNumber)}')`;
        map<Encoding> queryParamEncoding = {"$select": {style: FORM, explode: false}, "$expand": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Deletes a specific condition supplement.
    #
    # + ConditionRecord - Number of Condition Record
    # + ConditionSequentialNumber - Sequential number of the condition
    # + headers - Headers to be sent with the request 
    # + return - Success 
    remote isolated function deleteA_SlsPrcgCndnRecdSuplmnt(string ConditionRecord, string ConditionSequentialNumber, map<string|string[]> headers = {}) returns error? {
        string resourcePath = string `/A_SlsPrcgCndnRecdSuplmnt(ConditionRecord='${getEncodedUri(ConditionRecord)}',ConditionSequentialNumber='${getEncodedUri(ConditionSequentialNumber)}')`;
        return self.clientEp->delete(resourcePath, headers = headers);
    }

    # Updates a specific condition supplement.
    #
    # + ConditionRecord - Number of Condition Record
    # + ConditionSequentialNumber - Sequential number of the condition
    # + headers - Headers to be sent with the request 
    # + payload - New property values 
    # + return - Success 
    remote isolated function patchA_SlsPrcgCndnRecdSuplmnt(string ConditionRecord, string ConditionSequentialNumber, Modified\ A_SlsPrcgCndnRecdSuplmntType payload, map<string|string[]> headers = {}) returns error? {
        string resourcePath = string `/A_SlsPrcgCndnRecdSuplmnt(ConditionRecord='${getEncodedUri(ConditionRecord)}',ConditionSequentialNumber='${getEncodedUri(ConditionSequentialNumber)}')`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->patch(resourcePath, request, headers);
    }

    # Reads validity of the condition record for a specific condition supplement.
    #
    # + ConditionRecord - Number of Condition Record
    # + ConditionSequentialNumber - Sequential number of the condition
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Retrieved entities 
    remote isolated function listSlsPrcgCndnRecdValiditiesOfA_SlsPrcgCndnRecdSuplmnt(string ConditionRecord, string ConditionSequentialNumber, map<string|string[]> headers = {}, *ListSlsPrcgCndnRecdValiditiesOfA_SlsPrcgCndnRecdSuplmntQueries queries) returns CollectionOfA_SlsPrcgCndnRecdValidityWrapper|error {
        string resourcePath = string `/A_SlsPrcgCndnRecdSuplmnt(ConditionRecord='${getEncodedUri(ConditionRecord)}',ConditionSequentialNumber='${getEncodedUri(ConditionSequentialNumber)}')/to_SlsPrcgCndnRecdValidity`;
        map<Encoding> queryParamEncoding = {"$orderby": {style: FORM, explode: false}, "$select": {style: FORM, explode: false}, "$expand": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Reads the pricing scales of a specific condition supplement.
    #
    # + ConditionRecord - Number of Condition Record
    # + ConditionSequentialNumber - Sequential number of the condition
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Retrieved entities 
    remote isolated function listSlsPrcgCndnRecordScalesOfA_SlsPrcgCndnRecdSuplmnt(string ConditionRecord, string ConditionSequentialNumber, map<string|string[]> headers = {}, *ListSlsPrcgCndnRecordScalesOfA_SlsPrcgCndnRecdSuplmntQueries queries) returns CollectionOfA_SlsPrcgCndnRecordScaleWrapper|error {
        string resourcePath = string `/A_SlsPrcgCndnRecdSuplmnt(ConditionRecord='${getEncodedUri(ConditionRecord)}',ConditionSequentialNumber='${getEncodedUri(ConditionSequentialNumber)}')/to_SlsPrcgCndnRecordScale`;
        map<Encoding> queryParamEncoding = {"$orderby": {style: FORM, explode: false}, "$select": {style: FORM, explode: false}, "$expand": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Creates one or more pricing scales for a specific condition supplement.
    #
    # + ConditionRecord - Number of Condition Record
    # + ConditionSequentialNumber - Sequential number of the condition
    # + headers - Headers to be sent with the request 
    # + payload - New entity 
    # + return - Created entity 
    remote isolated function createSlsPrcgCndnRecordScaleOfA_SlsPrcgCndnRecdSuplmnt(string ConditionRecord, string ConditionSequentialNumber, CreateA_SlsPrcgCndnRecordScale payload, map<string|string[]> headers = {}) returns A_SlsPrcgCndnRecordScaleWrapper|error {
        string resourcePath = string `/A_SlsPrcgCndnRecdSuplmnt(ConditionRecord='${getEncodedUri(ConditionRecord)}',ConditionSequentialNumber='${getEncodedUri(ConditionSequentialNumber)}')/to_SlsPrcgCndnRecordScale`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Reads the pricing supplement texts of a specific condition supplement.
    #
    # + ConditionRecord - Number of Condition Record
    # + ConditionSequentialNumber - Sequential number of the condition
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Retrieved entities 
    remote isolated function listSlsPrcgCndnSupplementTextsOfA_SlsPrcgCndnRecdSuplmnt(string ConditionRecord, string ConditionSequentialNumber, map<string|string[]> headers = {}, *ListSlsPrcgCndnSupplementTextsOfA_SlsPrcgCndnRecdSuplmntQueries queries) returns CollectionOfA_SlsPrcgCndnSupplementTextWrapper|error {
        string resourcePath = string `/A_SlsPrcgCndnRecdSuplmnt(ConditionRecord='${getEncodedUri(ConditionRecord)}',ConditionSequentialNumber='${getEncodedUri(ConditionSequentialNumber)}')/to_SlsPrcgCndnSupplementText`;
        map<Encoding> queryParamEncoding = {"$orderby": {style: FORM, explode: false}, "$select": {style: FORM, explode: false}, "$expand": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Creates one or more pricing supplement texts for a specific condition supplement.
    #
    # + ConditionRecord - Number of Condition Record
    # + ConditionSequentialNumber - Sequential number of the condition
    # + headers - Headers to be sent with the request 
    # + payload - New entity 
    # + return - Created entity 
    remote isolated function createSlsPrcgCndnSupplementTextOfA_SlsPrcgCndnRecdSuplmnt(string ConditionRecord, string ConditionSequentialNumber, CreateA_SlsPrcgCndnSupplementText payload, map<string|string[]> headers = {}) returns A_SlsPrcgCndnSupplementTextWrapper|error {
        string resourcePath = string `/A_SlsPrcgCndnRecdSuplmnt(ConditionRecord='${getEncodedUri(ConditionRecord)}',ConditionSequentialNumber='${getEncodedUri(ConditionSequentialNumber)}')/to_SlsPrcgCndnSupplementText`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Reads the condition record for a specific condition supplement.
    #
    # + ConditionRecord - Number of Condition Record
    # + ConditionSequentialNumber - Sequential number of the condition
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Retrieved entity 
    remote isolated function getSlsPrcgConditionRecordOfA_SlsPrcgCndnRecdSuplmnt(string ConditionRecord, string ConditionSequentialNumber, map<string|string[]> headers = {}, *GetSlsPrcgConditionRecordOfA_SlsPrcgCndnRecdSuplmntQueries queries) returns A_SlsPrcgConditionRecordWrapper|error {
        string resourcePath = string `/A_SlsPrcgCndnRecdSuplmnt(ConditionRecord='${getEncodedUri(ConditionRecord)}',ConditionSequentialNumber='${getEncodedUri(ConditionSequentialNumber)}')/to_SlsPrcgConditionRecord`;
        map<Encoding> queryParamEncoding = {"$select": {style: FORM, explode: false}, "$expand": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Reads validity of all condition records in the system.
    #
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Retrieved entities 
    remote isolated function listA_SlsPrcgCndnRecdValidities(map<string|string[]> headers = {}, *ListA_SlsPrcgCndnRecdValiditiesQueries queries) returns CollectionOfA_SlsPrcgCndnRecdValidityWrapper|error {
        string resourcePath = string `/A_SlsPrcgCndnRecdValidity`;
        map<Encoding> queryParamEncoding = {"$orderby": {style: FORM, explode: false}, "$select": {style: FORM, explode: false}, "$expand": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Reads the validity of a specific condition record.
    #
    # + ConditionRecord - Number of Condition Record
    # + ConditionValidityEndDate - Validity end date of the condition record
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Retrieved entity 
    remote isolated function getA_SlsPrcgCndnRecdValidity(string ConditionRecord, string ConditionValidityEndDate, map<string|string[]> headers = {}, *GetA_SlsPrcgCndnRecdValidityQueries queries) returns A_SlsPrcgCndnRecdValidityWrapper|error {
        string resourcePath = string `/A_SlsPrcgCndnRecdValidity(ConditionRecord='${getEncodedUri(ConditionRecord)}',ConditionValidityEndDate=datetime'${getEncodedUri(ConditionValidityEndDate)}')`;
        map<Encoding> queryParamEncoding = {"$select": {style: FORM, explode: false}, "$expand": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Updates the validity period of a specific condition record.
    #
    # + ConditionRecord - Number of Condition Record
    # + ConditionValidityEndDate - Validity end date of the condition record
    # + headers - Headers to be sent with the request 
    # + payload - New property values 
    # + return - Success 
    remote isolated function patchA_SlsPrcgCndnRecdValidity(string ConditionRecord, string ConditionValidityEndDate, Modified\ A_SlsPrcgCndnRecdValidityType payload, map<string|string[]> headers = {}) returns error? {
        string resourcePath = string `/A_SlsPrcgCndnRecdValidity(ConditionRecord='${getEncodedUri(ConditionRecord)}',ConditionValidityEndDate=datetime'${getEncodedUri(ConditionValidityEndDate)}')`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->patch(resourcePath, request, headers);
    }

    # Reads the condition supplements for a specific condition record validity period.
    #
    # + ConditionRecord - Number of Condition Record
    # + ConditionValidityEndDate - Validity end date of the condition record
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Retrieved entities 
    remote isolated function listSlsPrcgCndnRecdSuplmntsOfA_SlsPrcgCndnRecdValidity(string ConditionRecord, string ConditionValidityEndDate, map<string|string[]> headers = {}, *ListSlsPrcgCndnRecdSuplmntsOfA_SlsPrcgCndnRecdValidityQueries queries) returns CollectionOfA_SlsPrcgCndnRecdSuplmntWrapper|error {
        string resourcePath = string `/A_SlsPrcgCndnRecdValidity(ConditionRecord='${getEncodedUri(ConditionRecord)}',ConditionValidityEndDate=datetime'${getEncodedUri(ConditionValidityEndDate)}')/to_SlsPrcgCndnRecdSuplmnt`;
        map<Encoding> queryParamEncoding = {"$orderby": {style: FORM, explode: false}, "$select": {style: FORM, explode: false}, "$expand": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Creates one or more condition supplements for a specific condition record validity period.
    #
    # + ConditionRecord - Number of Condition Record
    # + ConditionValidityEndDate - Validity end date of the condition record
    # + headers - Headers to be sent with the request 
    # + payload - New entity 
    # + return - Created entity 
    remote isolated function createSlsPrcgCndnRecdSuplmntOfA_SlsPrcgCndnRecdValidity(string ConditionRecord, string ConditionValidityEndDate, CreateA_SlsPrcgCndnRecdSuplmnt payload, map<string|string[]> headers = {}) returns A_SlsPrcgCndnRecdSuplmntWrapper|error {
        string resourcePath = string `/A_SlsPrcgCndnRecdValidity(ConditionRecord='${getEncodedUri(ConditionRecord)}',ConditionValidityEndDate=datetime'${getEncodedUri(ConditionValidityEndDate)}')/to_SlsPrcgCndnRecdSuplmnt`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Reads the condition record for a specific condition record validity period.
    #
    # + ConditionRecord - Number of Condition Record
    # + ConditionValidityEndDate - Validity end date of the condition record
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Retrieved entity 
    remote isolated function getSlsPrcgConditionRecordOfA_SlsPrcgCndnRecdValidity(string ConditionRecord, string ConditionValidityEndDate, map<string|string[]> headers = {}, *GetSlsPrcgConditionRecordOfA_SlsPrcgCndnRecdValidityQueries queries) returns A_SlsPrcgConditionRecordWrapper|error {
        string resourcePath = string `/A_SlsPrcgCndnRecdValidity(ConditionRecord='${getEncodedUri(ConditionRecord)}',ConditionValidityEndDate=datetime'${getEncodedUri(ConditionValidityEndDate)}')/to_SlsPrcgConditionRecord`;
        map<Encoding> queryParamEncoding = {"$select": {style: FORM, explode: false}, "$expand": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Reads all pricing scales in the system.
    #
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Retrieved entities 
    remote isolated function listA_SlsPrcgCndnRecordScales(map<string|string[]> headers = {}, *ListA_SlsPrcgCndnRecordScalesQueries queries) returns CollectionOfA_SlsPrcgCndnRecordScaleWrapper|error {
        string resourcePath = string `/A_SlsPrcgCndnRecordScale`;
        map<Encoding> queryParamEncoding = {"$orderby": {style: FORM, explode: false}, "$select": {style: FORM, explode: false}, "$expand": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Creates one or more pricing scales.
    #
    # + headers - Headers to be sent with the request 
    # + payload - New entity 
    # + return - Created entity 
    remote isolated function createA_SlsPrcgCndnRecordScale(CreateA_SlsPrcgCndnRecordScale payload, map<string|string[]> headers = {}) returns A_SlsPrcgCndnRecordScaleWrapper|error {
        string resourcePath = string `/A_SlsPrcgCndnRecordScale`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Reads a specific pricing scale.
    #
    # + ConditionRecord - Number of Condition Record
    # + ConditionSequentialNumber - Sequential number of the condition
    # + ConditionScaleLine - Current number of the line scale
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Retrieved entity 
    remote isolated function getA_SlsPrcgCndnRecordScale(string ConditionRecord, string ConditionSequentialNumber, string ConditionScaleLine, map<string|string[]> headers = {}, *GetA_SlsPrcgCndnRecordScaleQueries queries) returns A_SlsPrcgCndnRecordScaleWrapper|error {
        string resourcePath = string `/A_SlsPrcgCndnRecordScale(ConditionRecord='${getEncodedUri(ConditionRecord)}',ConditionSequentialNumber='${getEncodedUri(ConditionSequentialNumber)}',ConditionScaleLine='${getEncodedUri(ConditionScaleLine)}')`;
        map<Encoding> queryParamEncoding = {"$select": {style: FORM, explode: false}, "$expand": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Deletes a specific pricing scale.
    #
    # + ConditionRecord - Number of Condition Record
    # + ConditionSequentialNumber - Sequential number of the condition
    # + ConditionScaleLine - Current number of the line scale
    # + headers - Headers to be sent with the request 
    # + return - Success 
    remote isolated function deleteA_SlsPrcgCndnRecordScale(string ConditionRecord, string ConditionSequentialNumber, string ConditionScaleLine, map<string|string[]> headers = {}) returns error? {
        string resourcePath = string `/A_SlsPrcgCndnRecordScale(ConditionRecord='${getEncodedUri(ConditionRecord)}',ConditionSequentialNumber='${getEncodedUri(ConditionSequentialNumber)}',ConditionScaleLine='${getEncodedUri(ConditionScaleLine)}')`;
        return self.clientEp->delete(resourcePath, headers = headers);
    }

    # Updates a specific pricing scale.
    #
    # + ConditionRecord - Number of Condition Record
    # + ConditionSequentialNumber - Sequential number of the condition
    # + ConditionScaleLine - Current number of the line scale
    # + headers - Headers to be sent with the request 
    # + payload - New property values 
    # + return - Success 
    remote isolated function patchA_SlsPrcgCndnRecordScale(string ConditionRecord, string ConditionSequentialNumber, string ConditionScaleLine, Modified\ A_SlsPrcgCndnRecordScaleType payload, map<string|string[]> headers = {}) returns error? {
        string resourcePath = string `/A_SlsPrcgCndnRecordScale(ConditionRecord='${getEncodedUri(ConditionRecord)}',ConditionSequentialNumber='${getEncodedUri(ConditionSequentialNumber)}',ConditionScaleLine='${getEncodedUri(ConditionScaleLine)}')`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->patch(resourcePath, request, headers);
    }

    # Reads the condition supplement for a specific condition supplement pricing scale.
    #
    # + ConditionRecord - Number of Condition Record
    # + ConditionSequentialNumber - Sequential number of the condition
    # + ConditionScaleLine - Current number of the line scale
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Retrieved entity 
    remote isolated function getSlsPrcgCndnRecdSuplmntOfA_SlsPrcgCndnRecordScale(string ConditionRecord, string ConditionSequentialNumber, string ConditionScaleLine, map<string|string[]> headers = {}, *GetSlsPrcgCndnRecdSuplmntOfA_SlsPrcgCndnRecordScaleQueries queries) returns A_SlsPrcgCndnRecdSuplmntWrapper|error {
        string resourcePath = string `/A_SlsPrcgCndnRecordScale(ConditionRecord='${getEncodedUri(ConditionRecord)}',ConditionSequentialNumber='${getEncodedUri(ConditionSequentialNumber)}',ConditionScaleLine='${getEncodedUri(ConditionScaleLine)}')/to_SlsPrcgCndnRecdSuplmnt`;
        map<Encoding> queryParamEncoding = {"$select": {style: FORM, explode: false}, "$expand": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Reads the condition record for a specific pricing scale.
    #
    # + ConditionRecord - Number of Condition Record
    # + ConditionSequentialNumber - Sequential number of the condition
    # + ConditionScaleLine - Current number of the line scale
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Retrieved entity 
    remote isolated function getSlsPrcgConditionRecordOfA_SlsPrcgCndnRecordScale(string ConditionRecord, string ConditionSequentialNumber, string ConditionScaleLine, map<string|string[]> headers = {}, *GetSlsPrcgConditionRecordOfA_SlsPrcgCndnRecordScaleQueries queries) returns A_SlsPrcgConditionRecordWrapper|error {
        string resourcePath = string `/A_SlsPrcgCndnRecordScale(ConditionRecord='${getEncodedUri(ConditionRecord)}',ConditionSequentialNumber='${getEncodedUri(ConditionSequentialNumber)}',ConditionScaleLine='${getEncodedUri(ConditionScaleLine)}')/to_SlsPrcgConditionRecord`;
        map<Encoding> queryParamEncoding = {"$select": {style: FORM, explode: false}, "$expand": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Reads all pricing supplement texts in the system.
    #
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Retrieved entities 
    remote isolated function listA_SlsPrcgCndnSupplementTexts(map<string|string[]> headers = {}, *ListA_SlsPrcgCndnSupplementTextsQueries queries) returns CollectionOfA_SlsPrcgCndnSupplementTextWrapper|error {
        string resourcePath = string `/A_SlsPrcgCndnSupplementText`;
        map<Encoding> queryParamEncoding = {"$orderby": {style: FORM, explode: false}, "$select": {style: FORM, explode: false}, "$expand": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Creates one or more pricing supplement texts.
    #
    # + headers - Headers to be sent with the request 
    # + payload - New entity 
    # + return - Created entity 
    remote isolated function createA_SlsPrcgCndnSupplementText(CreateA_SlsPrcgCndnSupplementText payload, map<string|string[]> headers = {}) returns A_SlsPrcgCndnSupplementTextWrapper|error {
        string resourcePath = string `/A_SlsPrcgCndnSupplementText`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Reads a specific pricing supplement text.
    #
    # + ConditionRecord - Number of Condition Record
    # + ConditionSequentialNumber - Sequential number of the condition
    # + Language - Language Key
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Retrieved entity 
    remote isolated function getA_SlsPrcgCndnSupplementText(string ConditionRecord, string ConditionSequentialNumber, string Language, map<string|string[]> headers = {}, *GetA_SlsPrcgCndnSupplementTextQueries queries) returns A_SlsPrcgCndnSupplementTextWrapper|error {
        string resourcePath = string `/A_SlsPrcgCndnSupplementText(ConditionRecord='${getEncodedUri(ConditionRecord)}',ConditionSequentialNumber='${getEncodedUri(ConditionSequentialNumber)}',Language='${getEncodedUri(Language)}')`;
        map<Encoding> queryParamEncoding = {"$select": {style: FORM, explode: false}, "$expand": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Deletes a specific pricing supplement text.
    #
    # + ConditionRecord - Number of Condition Record
    # + ConditionSequentialNumber - Sequential number of the condition
    # + Language - Language Key
    # + headers - Headers to be sent with the request 
    # + return - Success 
    remote isolated function deleteA_SlsPrcgCndnSupplementText(string ConditionRecord, string ConditionSequentialNumber, string Language, map<string|string[]> headers = {}) returns error? {
        string resourcePath = string `/A_SlsPrcgCndnSupplementText(ConditionRecord='${getEncodedUri(ConditionRecord)}',ConditionSequentialNumber='${getEncodedUri(ConditionSequentialNumber)}',Language='${getEncodedUri(Language)}')`;
        return self.clientEp->delete(resourcePath, headers = headers);
    }

    # Updates a specific pricing supplement text.
    #
    # + ConditionRecord - Number of Condition Record
    # + ConditionSequentialNumber - Sequential number of the condition
    # + Language - Language Key
    # + headers - Headers to be sent with the request 
    # + payload - New property values 
    # + return - Success 
    remote isolated function patchA_SlsPrcgCndnSupplementText(string ConditionRecord, string ConditionSequentialNumber, string Language, Modified\ A_SlsPrcgCndnSupplementTextType payload, map<string|string[]> headers = {}) returns error? {
        string resourcePath = string `/A_SlsPrcgCndnSupplementText(ConditionRecord='${getEncodedUri(ConditionRecord)}',ConditionSequentialNumber='${getEncodedUri(ConditionSequentialNumber)}',Language='${getEncodedUri(Language)}')`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->patch(resourcePath, request, headers);
    }

    # Reads the condition record for a specific pricing supplement text.
    #
    # + ConditionRecord - Number of Condition Record
    # + ConditionSequentialNumber - Sequential number of the condition
    # + Language - Language Key
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Retrieved entity 
    remote isolated function getSlsPrcgCndnRecdSuplmntOfA_SlsPrcgCndnSupplementText(string ConditionRecord, string ConditionSequentialNumber, string Language, map<string|string[]> headers = {}, *GetSlsPrcgCndnRecdSuplmntOfA_SlsPrcgCndnSupplementTextQueries queries) returns A_SlsPrcgCndnRecdSuplmntWrapper|error {
        string resourcePath = string `/A_SlsPrcgCndnSupplementText(ConditionRecord='${getEncodedUri(ConditionRecord)}',ConditionSequentialNumber='${getEncodedUri(ConditionSequentialNumber)}',Language='${getEncodedUri(Language)}')/to_SlsPrcgCndnRecdSuplmnt`;
        map<Encoding> queryParamEncoding = {"$select": {style: FORM, explode: false}, "$expand": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Reads all condition records in the system.
    #
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Retrieved entities 
    remote isolated function listA_SlsPrcgConditionRecords(map<string|string[]> headers = {}, *ListA_SlsPrcgConditionRecordsQueries queries) returns CollectionOfA_SlsPrcgConditionRecordWrapper|error {
        string resourcePath = string `/A_SlsPrcgConditionRecord`;
        map<Encoding> queryParamEncoding = {"$orderby": {style: FORM, explode: false}, "$select": {style: FORM, explode: false}, "$expand": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Creates one or more condition records.
    #
    # + headers - Headers to be sent with the request 
    # + payload - New entity 
    # + return - Created entity 
    remote isolated function createA_SlsPrcgConditionRecord(CreateA_SlsPrcgConditionRecord payload, map<string|string[]> headers = {}) returns A_SlsPrcgConditionRecordWrapper|error {
        string resourcePath = string `/A_SlsPrcgConditionRecord`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Reads a specific condition record.
    #
    # + ConditionRecord - Number of Condition Record
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Retrieved entity 
    remote isolated function getA_SlsPrcgConditionRecord(string ConditionRecord, map<string|string[]> headers = {}, *GetA_SlsPrcgConditionRecordQueries queries) returns A_SlsPrcgConditionRecordWrapper|error {
        string resourcePath = string `/A_SlsPrcgConditionRecord('${getEncodedUri(ConditionRecord)}')`;
        map<Encoding> queryParamEncoding = {"$select": {style: FORM, explode: false}, "$expand": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Deletes a specific condition record.
    #
    # + ConditionRecord - Number of Condition Record
    # + headers - Headers to be sent with the request 
    # + return - Success 
    remote isolated function deleteA_SlsPrcgConditionRecord(string ConditionRecord, map<string|string[]> headers = {}) returns error? {
        string resourcePath = string `/A_SlsPrcgConditionRecord('${getEncodedUri(ConditionRecord)}')`;
        return self.clientEp->delete(resourcePath, headers = headers);
    }

    # Updates a specific condition record.
    #
    # + ConditionRecord - Number of Condition Record
    # + headers - Headers to be sent with the request 
    # + payload - New property values 
    # + return - Success 
    remote isolated function patchA_SlsPrcgConditionRecord(string ConditionRecord, Modified\ A_SlsPrcgConditionRecordType payload, map<string|string[]> headers = {}) returns error? {
        string resourcePath = string `/A_SlsPrcgConditionRecord('${getEncodedUri(ConditionRecord)}')`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->patch(resourcePath, request, headers);
    }

    # Reads the condition supplements of a specific condition record.
    #
    # + ConditionRecord - Number of Condition Record
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Retrieved entities 
    remote isolated function listSlsPrcgCndnRecdSuplmntsOfA_SlsPrcgConditionRecord(string ConditionRecord, map<string|string[]> headers = {}, *ListSlsPrcgCndnRecdSuplmntsOfA_SlsPrcgConditionRecordQueries queries) returns CollectionOfA_SlsPrcgCndnRecdSuplmntWrapper|error {
        string resourcePath = string `/A_SlsPrcgConditionRecord('${getEncodedUri(ConditionRecord)}')/to_SlsPrcgCndnRecdSuplmnt`;
        map<Encoding> queryParamEncoding = {"$orderby": {style: FORM, explode: false}, "$select": {style: FORM, explode: false}, "$expand": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Creates one or more condition supplements for a specific condition record.
    #
    # + ConditionRecord - Number of Condition Record
    # + headers - Headers to be sent with the request 
    # + payload - New entity 
    # + return - Created entity 
    remote isolated function createSlsPrcgCndnRecdSuplmntOfA_SlsPrcgConditionRecord(string ConditionRecord, CreateA_SlsPrcgCndnRecdSuplmnt payload, map<string|string[]> headers = {}) returns A_SlsPrcgCndnRecdSuplmntWrapper|error {
        string resourcePath = string `/A_SlsPrcgConditionRecord('${getEncodedUri(ConditionRecord)}')/to_SlsPrcgCndnRecdSuplmnt`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Reads the validity of a specific condition record.
    #
    # + ConditionRecord - Number of Condition Record
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Retrieved entities 
    remote isolated function listSlsPrcgCndnRecdValiditiesOfA_SlsPrcgConditionRecord(string ConditionRecord, map<string|string[]> headers = {}, *ListSlsPrcgCndnRecdValiditiesOfA_SlsPrcgConditionRecordQueries queries) returns CollectionOfA_SlsPrcgCndnRecdValidityWrapper|error {
        string resourcePath = string `/A_SlsPrcgConditionRecord('${getEncodedUri(ConditionRecord)}')/to_SlsPrcgCndnRecdValidity`;
        map<Encoding> queryParamEncoding = {"$orderby": {style: FORM, explode: false}, "$select": {style: FORM, explode: false}, "$expand": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Reads the pricing scales of a specific condition record.
    #
    # + ConditionRecord - Number of Condition Record
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Retrieved entities 
    remote isolated function listSlsPrcgCndnRecordScalesOfA_SlsPrcgConditionRecord(string ConditionRecord, map<string|string[]> headers = {}, *ListSlsPrcgCndnRecordScalesOfA_SlsPrcgConditionRecordQueries queries) returns CollectionOfA_SlsPrcgCndnRecordScaleWrapper|error {
        string resourcePath = string `/A_SlsPrcgConditionRecord('${getEncodedUri(ConditionRecord)}')/to_SlsPrcgCndnRecordScale`;
        map<Encoding> queryParamEncoding = {"$orderby": {style: FORM, explode: false}, "$select": {style: FORM, explode: false}, "$expand": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Creates one or more pricing scales for a specific condition record.
    #
    # + ConditionRecord - Number of Condition Record
    # + headers - Headers to be sent with the request 
    # + payload - New entity 
    # + return - Created entity 
    remote isolated function createSlsPrcgCndnRecordScaleOfA_SlsPrcgConditionRecord(string ConditionRecord, CreateA_SlsPrcgCndnRecordScale payload, map<string|string[]> headers = {}) returns A_SlsPrcgCndnRecordScaleWrapper|error {
        string resourcePath = string `/A_SlsPrcgConditionRecord('${getEncodedUri(ConditionRecord)}')/to_SlsPrcgCndnRecordScale`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Reads the pricing record texts of a specific condition record.
    #
    # + ConditionRecord - Number of Condition Record
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Retrieved entities 
    remote isolated function listSlsPrcgConditionRecordTextsOfA_SlsPrcgConditionRecord(string ConditionRecord, map<string|string[]> headers = {}, *ListSlsPrcgConditionRecordTextsOfA_SlsPrcgConditionRecordQueries queries) returns CollectionOfA_SlsPrcgConditionRecordTextWrapper|error {
        string resourcePath = string `/A_SlsPrcgConditionRecord('${getEncodedUri(ConditionRecord)}')/to_SlsPrcgConditionRecordText`;
        map<Encoding> queryParamEncoding = {"$orderby": {style: FORM, explode: false}, "$select": {style: FORM, explode: false}, "$expand": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Creates one or more pricing record texts for a specific condition record.
    #
    # + ConditionRecord - Number of Condition Record
    # + headers - Headers to be sent with the request 
    # + payload - New entity 
    # + return - Created entity 
    remote isolated function createSlsPrcgConditionRecordTextOfA_SlsPrcgConditionRecord(string ConditionRecord, CreateA_SlsPrcgConditionRecordText payload, map<string|string[]> headers = {}) returns A_SlsPrcgConditionRecordTextWrapper|error {
        string resourcePath = string `/A_SlsPrcgConditionRecord('${getEncodedUri(ConditionRecord)}')/to_SlsPrcgConditionRecordText`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Reads all pricing record texts in the system.
    #
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Retrieved entities 
    remote isolated function listA_SlsPrcgConditionRecordTexts(map<string|string[]> headers = {}, *ListA_SlsPrcgConditionRecordTextsQueries queries) returns CollectionOfA_SlsPrcgConditionRecordTextWrapper|error {
        string resourcePath = string `/A_SlsPrcgConditionRecordText`;
        map<Encoding> queryParamEncoding = {"$orderby": {style: FORM, explode: false}, "$select": {style: FORM, explode: false}, "$expand": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Creates one or more pricing record texts.
    #
    # + headers - Headers to be sent with the request 
    # + payload - New entity 
    # + return - Created entity 
    remote isolated function createA_SlsPrcgConditionRecordText(CreateA_SlsPrcgConditionRecordText payload, map<string|string[]> headers = {}) returns A_SlsPrcgConditionRecordTextWrapper|error {
        string resourcePath = string `/A_SlsPrcgConditionRecordText`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Reads a specific pricing record text.
    #
    # + ConditionRecord - Number of Condition Record
    # + ConditionSequentialNumber - Sequential number of the condition
    # + Language - Language Key
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Retrieved entity 
    remote isolated function getA_SlsPrcgConditionRecordText(string ConditionRecord, string ConditionSequentialNumber, string Language, map<string|string[]> headers = {}, *GetA_SlsPrcgConditionRecordTextQueries queries) returns A_SlsPrcgConditionRecordTextWrapper|error {
        string resourcePath = string `/A_SlsPrcgConditionRecordText(ConditionRecord='${getEncodedUri(ConditionRecord)}',ConditionSequentialNumber='${getEncodedUri(ConditionSequentialNumber)}',Language='${getEncodedUri(Language)}')`;
        map<Encoding> queryParamEncoding = {"$select": {style: FORM, explode: false}, "$expand": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Deletes a specific pricing record text.
    #
    # + ConditionRecord - Number of Condition Record
    # + ConditionSequentialNumber - Sequential number of the condition
    # + Language - Language Key
    # + headers - Headers to be sent with the request 
    # + return - Success 
    remote isolated function deleteA_SlsPrcgConditionRecordText(string ConditionRecord, string ConditionSequentialNumber, string Language, map<string|string[]> headers = {}) returns error? {
        string resourcePath = string `/A_SlsPrcgConditionRecordText(ConditionRecord='${getEncodedUri(ConditionRecord)}',ConditionSequentialNumber='${getEncodedUri(ConditionSequentialNumber)}',Language='${getEncodedUri(Language)}')`;
        return self.clientEp->delete(resourcePath, headers = headers);
    }

    # Updates a specific pricing record text.
    #
    # + ConditionRecord - Number of Condition Record
    # + ConditionSequentialNumber - Sequential number of the condition
    # + Language - Language Key
    # + headers - Headers to be sent with the request 
    # + payload - New property values 
    # + return - Success 
    remote isolated function patchA_SlsPrcgConditionRecordText(string ConditionRecord, string ConditionSequentialNumber, string Language, Modified\ A_SlsPrcgConditionRecordTextType payload, map<string|string[]> headers = {}) returns error? {
        string resourcePath = string `/A_SlsPrcgConditionRecordText(ConditionRecord='${getEncodedUri(ConditionRecord)}',ConditionSequentialNumber='${getEncodedUri(ConditionSequentialNumber)}',Language='${getEncodedUri(Language)}')`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->patch(resourcePath, request, headers);
    }

    # Reads the condition record for a specific pricing record text.
    #
    # + ConditionRecord - Number of Condition Record
    # + ConditionSequentialNumber - Sequential number of the condition
    # + Language - Language Key
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Retrieved entity 
    remote isolated function getSlsPrcgConditionRecordOfA_SlsPrcgConditionRecordText(string ConditionRecord, string ConditionSequentialNumber, string Language, map<string|string[]> headers = {}, *GetSlsPrcgConditionRecordOfA_SlsPrcgConditionRecordTextQueries queries) returns A_SlsPrcgConditionRecordWrapper|error {
        string resourcePath = string `/A_SlsPrcgConditionRecordText(ConditionRecord='${getEncodedUri(ConditionRecord)}',ConditionSequentialNumber='${getEncodedUri(ConditionSequentialNumber)}',Language='${getEncodedUri(Language)}')/to_SlsPrcgConditionRecord`;
        map<Encoding> queryParamEncoding = {"$select": {style: FORM, explode: false}, "$expand": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Send a group of requests
    #
    # + headers - Headers to be sent with the request 
    # + request - Batch request 
    # + return - Batch response 
    remote isolated function performBatchOperation(http:Request request, map<string|string[]> headers = {}) returns http:Response|error {
        string resourcePath = string `/$batch`;
        // TODO: Update the request as needed;
        return self.clientEp->post(resourcePath, request, headers);
    }
}
