[package]
org = "integration_samples"
name = "salesforce_to_sap"
version = "0.1.0"
distribution = "2201.8.2"

[[dependency]]
org = "ballerinax"
name = "sap.s4hana.api_sales_order_srv"
version = "1.0.0"
repository = "local"
