name: Daily build

on:
  schedule:
    - cron: "30 2 * * *"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  call_workflow:
    name: Run Daily Build Workflow
    uses: ballerina-platform/ballerina-library/.github/workflows/s4hana-daily-build-connector-template.yml@main
    secrets: inherit
    with:
      hana-connector-group: sales