name: Publish Single Connector to the Ballerina Dev\Stage Central

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Select Environment
        required: true
        options:
          - DEV CENTRAL
          - STAGE CENTRAL
      connector:
        type: choice
        description: Select Connector
        required: true
        options:
          - api_salesdistrict_srv
          - api_salesorganization_srv
          - api_sales_order_srv
          - api_sd_sa_soldtopartydetn
          - salesarea_0001
          - api_sd_incoterms_srv
          - api_sales_inquiry_srv
          - api_sales_quotation_srv
          - api_sales_order_simulation_srv
          - ce_salesorder_0001

jobs:
  call_workflow:
    name: Run Dev\Stage Central Publish Workflow
    if: ${{ github.repository_owner == 'ballerina-platform' }}
    uses: ballerina-platform/ballerina-library/.github/workflows/s4hana-dev-stage-central-single-publish-template.yml@s4hana
    secrets: inherit
    with:
      environment: ${{ inputs.environment }}
      hana-connector-group: sales
      hana-connector-name: ${{ inputs.connector }}
