name: Publish Release

on:
  workflow_dispatch:
    inputs:
      connector:
        type: choice
        description: Select Connector
        required: true
        options:
          - api_salesdistrict_srv
          - api_salesorganization_srv
          - api_sales_order_srv
          - api_sd_sa_soldtopartydetn
          - salesarea_0001
          - api_sd_incoterms_srv
          - api_sales_inquiry_srv
          - api_sales_quotation_srv
          - api_sales_order_simulation_srv
          - ce_salesorder_0001

jobs:
  call_workflow:
    name: Run Release Workflow
    if: ${{ github.repository_owner == 'ballerina-platform' }}
    uses: ballerina-platform/ballerina-library/.github/workflows/s4hana-release-template.yml@main
    secrets: inherit
    with:
      hana-connector-group: sales
      hana-connector-name: ${{ inputs.connector }}
