name: Trivy

on:
  workflow_dispatch:
  schedule:
    - cron: "30 20 * * *"

jobs:
  call_workflow:
    name: Run Trivy Scan Workflow
    uses: ballerina-platform/ballerina-library/.github/workflows/s4hana-trivy-scan.yml@main
    secrets: inherit
    with:
      hana-connector-group: sales
